apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "event-worker.fullname" . }}-config
  labels:
    {{- include "event-worker.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_GROUP_ID: {{ .Values.kafka.groupId | quote }}
  KAFKA_TOPICS: {{ .Values.kafka.topics | quote }}
  KAFKA_AUTO_OFFSET_RESET: {{ .Values.kafka.autoOffsetReset | quote }}
  KAFKA_SESSION_TIMEOUT_MS: {{ .Values.kafka.sessionTimeoutMs | quote }}
  KAFKA_HEARTBEAT_INTERVAL_MS: {{ .Values.kafka.heartbeatIntervalMs | quote }}
