apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { { include "event-worker.fullname" . } }
  labels: { { - include "event-worker.labels" . | nindent 4 } }
spec:
  minAvailable: { { .Values.pdb.minAvailable } }
  selector:
    matchLabels: { { - include "event-worker.selectorLabels" . | nindent 6 } }
