apiVersion: v1
kind: Service
metadata:
  name: { { include "event-worker.fullname" . } }
  labels: { { - include "event-worker.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  selector: { { - include "event-worker.selectorLabels" . | nindent 4 } }
  ports:
    - name: metrics
      port: { { .Values.service.metricsPort } }
      targetPort: metrics
      protocol: TCP
