/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise AI System — REST API
 * Synchronous REST API for the Enterprise AI System. High-volume async flows use Kafka events (see asyncapi.yaml). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    DecisionIn,
    DecisionOut,
    HITLRequestSummary,
    HITLStatusResponse,
} from '../models/index';

export interface SubmitDecisionRequest {
    requestId: string;
    decisionIn: DecisionIn;
}

/**
 * 
 */
export class HitlApi extends runtime.BaseAPI {

    /**
     * Creates request options for hitlStatus without sending the request
     */
    async hitlStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/hitl/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * HITL subsystem health and queue depth
     */
    async hitlStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HITLStatusResponse>> {
        const requestOptions = await this.hitlStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * HITL subsystem health and queue depth
     */
    async hitlStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HITLStatusResponse> {
        const response = await this.hitlStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPendingRequests without sending the request
     */
    async listPendingRequestsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/hitl/requests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the pending requests awaiting an operator decision. Requires an operator JWT (role hitl-operator). Only the PII-masked context_summary is exposed per request; raw action_parameters never leave the gateway.
     * List pending HITL approval requests
     */
    async listPendingRequestsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<HITLRequestSummary>>> {
        const requestOptions = await this.listPendingRequestsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the pending requests awaiting an operator decision. Requires an operator JWT (role hitl-operator). Only the PII-masked context_summary is exposed per request; raw action_parameters never leave the gateway.
     * List pending HITL approval requests
     */
    async listPendingRequests(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<HITLRequestSummary>> {
        const response = await this.listPendingRequestsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitDecision without sending the request
     */
    async submitDecisionRequestOpts(requestParameters: SubmitDecisionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling submitDecision().'
            );
        }

        if (requestParameters['decisionIn'] == null) {
            throw new runtime.RequiredError(
                'decisionIn',
                'Required parameter "decisionIn" was null or undefined when calling submitDecision().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/hitl/requests/{request_id}/decision`;
        urlPath = urlPath.replace('{request_id}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['decisionIn'],
        };
    }

    /**
     * Submit an APPROVE or REJECT decision
     */
    async submitDecisionRaw(requestParameters: SubmitDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionOut>> {
        const requestOptions = await this.submitDecisionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Submit an APPROVE or REJECT decision
     */
    async submitDecision(requestParameters: SubmitDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionOut> {
        const response = await this.submitDecisionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
