/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise AI System — REST API
 * Synchronous REST API for the Enterprise AI System. High-volume async flows use Kafka events (see asyncapi.yaml). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    RequestIn,
    RequestOut,
} from '../models/index';

export interface GetRequestStatusRequest {
    requestId: string;
}

export interface SubmitRequestRequest {
    requestIn: RequestIn;
}

/**
 * 
 */
export class RequestsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getRequestStatus without sending the request
     */
    async getRequestStatusRequestOpts(requestParameters: GetRequestStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestId'] == null) {
            throw new runtime.RequiredError(
                'requestId',
                'Required parameter "requestId" was null or undefined when calling getRequestStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/requests/{request_id}`;
        urlPath = urlPath.replace('{request_id}', encodeURIComponent(String(requestParameters['requestId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Poll request processing status
     */
    async getRequestStatusRaw(requestParameters: GetRequestStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestOut>> {
        const requestOptions = await this.getRequestStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Poll request processing status
     */
    async getRequestStatus(requestParameters: GetRequestStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestOut> {
        const response = await this.getRequestStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitRequest without sending the request
     */
    async submitRequestRequestOpts(requestParameters: SubmitRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestIn'] == null) {
            throw new runtime.RequiredError(
                'requestIn',
                'Required parameter "requestIn" was null or undefined when calling submitRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/requests`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestIn'],
        };
    }

    /**
     * Accepts a request and publishes it to the async pipeline. Returns 202 immediately. Poll GET /v1/requests/{request_id} for the result. PII in the request body is masked before the event is published. 
     * Submit a domain request for async processing
     */
    async submitRequestRaw(requestParameters: SubmitRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestOut>> {
        const requestOptions = await this.submitRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Accepts a request and publishes it to the async pipeline. Returns 202 immediately. Poll GET /v1/requests/{request_id} for the result. PII in the request body is masked before the event is published. 
     * Submit a domain request for async processing
     */
    async submitRequest(requestParameters: SubmitRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestOut> {
        const response = await this.submitRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
