replicaCount: 1

image:
  pullPolicy: Always

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  kafkaLagTarget: "10000"

pdb:
  minAvailable: 1

kafka:
  bootstrapServers: "kafka.staging:9092"
  groupId: "event-worker-staging"

env:
  LOG_LEVEL: debug
