// ai_service.proto — gRPC contract for the AI Agent Service
// -----------------------------------------------------------
// This file is the source of truth for gRPC inter-service calls.
// Do NOT hand-write client or server stubs — generate them:
//
//   Go:     make gen-proto-go
//   Java:   mvn generate-sources  (protoc-maven-plugin)
//   Python: make gen-proto-python (grpcio-tools)
//
// When adding a new RPC:
//   1. Add the method and its request/response messages here.
//   2. Re-generate stubs for every language that consumes this service.
//   3. Update docs/api/grpc/README.md with the new method.
//
// Field numbering rules:
//   - Never reuse a field number once it has been released.
//   - Reserved numbers must be declared with `reserved` to prevent reuse.
//   - Use google.protobuf.Timestamp (not int64) for all timestamps.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: ai_service.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitTaskResponse_Status int32

const (
	SubmitTaskResponse_STATUS_UNSPECIFIED SubmitTaskResponse_Status = 0
	SubmitTaskResponse_COMPLETED          SubmitTaskResponse_Status = 1 // Agent finished — result is in `result_json`
	SubmitTaskResponse_HITL_REQUIRED      SubmitTaskResponse_Status = 2 // Risk score above threshold — `hitl_request_id` is set
	SubmitTaskResponse_REJECTED           SubmitTaskResponse_Status = 3 // Prompt rejected by guardrails (injection / policy)
)

// Enum value maps for SubmitTaskResponse_Status.
var (
	SubmitTaskResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "COMPLETED",
		2: "HITL_REQUIRED",
		3: "REJECTED",
	}
	SubmitTaskResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"COMPLETED":          1,
		"HITL_REQUIRED":      2,
		"REJECTED":           3,
	}
)

func (x SubmitTaskResponse_Status) Enum() *SubmitTaskResponse_Status {
	p := new(SubmitTaskResponse_Status)
	*p = x
	return p
}

func (x SubmitTaskResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmitTaskResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_proto_enumTypes[0].Descriptor()
}

func (SubmitTaskResponse_Status) Type() protoreflect.EnumType {
	return &file_ai_service_proto_enumTypes[0]
}

func (x SubmitTaskResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmitTaskResponse_Status.Descriptor instead.
func (SubmitTaskResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{1, 0}
}

type TaskProgressEvent_Phase int32

const (
	TaskProgressEvent_PHASE_UNSPECIFIED TaskProgressEvent_Phase = 0
	TaskProgressEvent_PLANNING          TaskProgressEvent_Phase = 1
	TaskProgressEvent_EXECUTING         TaskProgressEvent_Phase = 2
	TaskProgressEvent_AWAITING_HITL     TaskProgressEvent_Phase = 3
	TaskProgressEvent_COMPLETED         TaskProgressEvent_Phase = 4
	TaskProgressEvent_FAILED            TaskProgressEvent_Phase = 5
)

// Enum value maps for TaskProgressEvent_Phase.
var (
	TaskProgressEvent_Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PLANNING",
		2: "EXECUTING",
		3: "AWAITING_HITL",
		4: "COMPLETED",
		5: "FAILED",
	}
	TaskProgressEvent_Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PLANNING":          1,
		"EXECUTING":         2,
		"AWAITING_HITL":     3,
		"COMPLETED":         4,
		"FAILED":            5,
	}
)

func (x TaskProgressEvent_Phase) Enum() *TaskProgressEvent_Phase {
	p := new(TaskProgressEvent_Phase)
	*p = x
	return p
}

func (x TaskProgressEvent_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskProgressEvent_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_proto_enumTypes[1].Descriptor()
}

func (TaskProgressEvent_Phase) Type() protoreflect.EnumType {
	return &file_ai_service_proto_enumTypes[1]
}

func (x TaskProgressEvent_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskProgressEvent_Phase.Descriptor instead.
func (TaskProgressEvent_Phase) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{3, 0}
}

type HITLGetDecisionResponse_Decision int32

const (
	HITLGetDecisionResponse_DECISION_UNSPECIFIED HITLGetDecisionResponse_Decision = 0
	HITLGetDecisionResponse_PENDING              HITLGetDecisionResponse_Decision = 1
	HITLGetDecisionResponse_APPROVED             HITLGetDecisionResponse_Decision = 2
	HITLGetDecisionResponse_REJECTED             HITLGetDecisionResponse_Decision = 3
	HITLGetDecisionResponse_EXPIRED              HITLGetDecisionResponse_Decision = 4
)

// Enum value maps for HITLGetDecisionResponse_Decision.
var (
	HITLGetDecisionResponse_Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "PENDING",
		2: "APPROVED",
		3: "REJECTED",
		4: "EXPIRED",
	}
	HITLGetDecisionResponse_Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"PENDING":              1,
		"APPROVED":             2,
		"REJECTED":             3,
		"EXPIRED":              4,
	}
)

func (x HITLGetDecisionResponse_Decision) Enum() *HITLGetDecisionResponse_Decision {
	p := new(HITLGetDecisionResponse_Decision)
	*p = x
	return p
}

func (x HITLGetDecisionResponse_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HITLGetDecisionResponse_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_proto_enumTypes[2].Descriptor()
}

func (HITLGetDecisionResponse_Decision) Type() protoreflect.EnumType {
	return &file_ai_service_proto_enumTypes[2]
}

func (x HITLGetDecisionResponse_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HITLGetDecisionResponse_Decision.Descriptor instead.
func (HITLGetDecisionResponse_Decision) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{7, 0}
}

type SubmitTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-assigned correlation ID. Used for distributed tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// PII-masked prompt text (apply pii_filter before sending).
	Prompt string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Opaque JSON context forwarded to the agent unchanged.
	ContextJson string `protobuf:"bytes,3,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	// Caller's declared risk score [0.0–1.0]. Agent may override upward.
	CallerRiskScore float32 `protobuf:"fixed32,4,opt,name=caller_risk_score,json=callerRiskScore,proto3" json:"caller_risk_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitTaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SubmitTaskRequest) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

func (x *SubmitTaskRequest) GetCallerRiskScore() float32 {
	if x != nil {
		return x.CallerRiskScore
	}
	return 0
}

type SubmitTaskResponse struct {
	state  protoimpl.MessageState    `protogen:"open.v1"`
	Status SubmitTaskResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ai.v1.SubmitTaskResponse_Status" json:"status,omitempty"`
	TaskId string                    `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Present only when status == COMPLETED
	ResultJson string `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	// Present only when status == HITL_REQUIRED
	HitlRequestId string                 `protobuf:"bytes,4,opt,name=hitl_request_id,json=hitlRequestId,proto3" json:"hitl_request_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTaskResponse) GetStatus() SubmitTaskResponse_Status {
	if x != nil {
		return x.Status
	}
	return SubmitTaskResponse_STATUS_UNSPECIFIED
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitTaskResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *SubmitTaskResponse) GetHitlRequestId() string {
	if x != nil {
		return x.HitlRequestId
	}
	return ""
}

func (x *SubmitTaskResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type WatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTaskRequest) Reset() {
	*x = WatchTaskRequest{}
	mi := &file_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTaskRequest) ProtoMessage() {}

func (x *WatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTaskRequest.ProtoReflect.Descriptor instead.
func (*WatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *WatchTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskProgressEvent struct {
	state  protoimpl.MessageState  `protogen:"open.v1"`
	TaskId string                  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Phase  TaskProgressEvent_Phase `protobuf:"varint,2,opt,name=phase,proto3,enum=ai.v1.TaskProgressEvent_Phase" json:"phase,omitempty"`
	// Human-readable progress message (already PII-masked).
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Percentage complete [0–100]. -1 if unknown.
	ProgressPct   int32                  `protobuf:"varint,4,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgressEvent) Reset() {
	*x = TaskProgressEvent{}
	mi := &file_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgressEvent) ProtoMessage() {}

func (x *TaskProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgressEvent.ProtoReflect.Descriptor instead.
func (*TaskProgressEvent) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *TaskProgressEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgressEvent) GetPhase() TaskProgressEvent_Phase {
	if x != nil {
		return x.Phase
	}
	return TaskProgressEvent_PHASE_UNSPECIFIED
}

func (x *TaskProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskProgressEvent) GetProgressPct() int32 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

func (x *TaskProgressEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HITLSubmitRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ActionType string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	// PII-masked payload JSON.
	PayloadJson string  `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	RiskScore   float32 `protobuf:"fixed32,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	// ISO 8601 duration string, e.g. "PT5M" for 5 minutes.
	ApprovalTimeout string `protobuf:"bytes,5,opt,name=approval_timeout,json=approvalTimeout,proto3" json:"approval_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HITLSubmitRequest) Reset() {
	*x = HITLSubmitRequest{}
	mi := &file_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HITLSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HITLSubmitRequest) ProtoMessage() {}

func (x *HITLSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HITLSubmitRequest.ProtoReflect.Descriptor instead.
func (*HITLSubmitRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *HITLSubmitRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HITLSubmitRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *HITLSubmitRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *HITLSubmitRequest) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *HITLSubmitRequest) GetApprovalTimeout() string {
	if x != nil {
		return x.ApprovalTimeout
	}
	return ""
}

type HITLSubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HitlRequestId string                 `protobuf:"bytes,1,opt,name=hitl_request_id,json=hitlRequestId,proto3" json:"hitl_request_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HITLSubmitResponse) Reset() {
	*x = HITLSubmitResponse{}
	mi := &file_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HITLSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HITLSubmitResponse) ProtoMessage() {}

func (x *HITLSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HITLSubmitResponse.ProtoReflect.Descriptor instead.
func (*HITLSubmitResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *HITLSubmitResponse) GetHitlRequestId() string {
	if x != nil {
		return x.HitlRequestId
	}
	return ""
}

func (x *HITLSubmitResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type HITLGetDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HitlRequestId string                 `protobuf:"bytes,1,opt,name=hitl_request_id,json=hitlRequestId,proto3" json:"hitl_request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HITLGetDecisionRequest) Reset() {
	*x = HITLGetDecisionRequest{}
	mi := &file_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HITLGetDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HITLGetDecisionRequest) ProtoMessage() {}

func (x *HITLGetDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HITLGetDecisionRequest.ProtoReflect.Descriptor instead.
func (*HITLGetDecisionRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *HITLGetDecisionRequest) GetHitlRequestId() string {
	if x != nil {
		return x.HitlRequestId
	}
	return ""
}

type HITLGetDecisionResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Decision      HITLGetDecisionResponse_Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=ai.v1.HITLGetDecisionResponse_Decision" json:"decision,omitempty"`
	ReviewerId    string                           `protobuf:"bytes,2,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	Reason        string                           `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	DecidedAt     *timestamppb.Timestamp           `protobuf:"bytes,4,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HITLGetDecisionResponse) Reset() {
	*x = HITLGetDecisionResponse{}
	mi := &file_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HITLGetDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HITLGetDecisionResponse) ProtoMessage() {}

func (x *HITLGetDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HITLGetDecisionResponse.ProtoReflect.Descriptor instead.
func (*HITLGetDecisionResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *HITLGetDecisionResponse) GetDecision() HITLGetDecisionResponse_Decision {
	if x != nil {
		return x.Decision
	}
	return HITLGetDecisionResponse_DECISION_UNSPECIFIED
}

func (x *HITLGetDecisionResponse) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *HITLGetDecisionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HITLGetDecisionResponse) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

var File_ai_service_proto protoreflect.FileDescriptor

const file_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x10ai_service.proto\x12\x05ai.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x01\n" +
	"\x11SubmitTaskRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12!\n" +
	"\fcontext_json\x18\x03 \x01(\tR\vcontextJson\x12*\n" +
	"\x11caller_risk_score\x18\x04 \x01(\x02R\x0fcallerRiskScore\"\xbd\x02\n" +
	"\x12SubmitTaskResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .ai.v1.SubmitTaskResponse.StatusR\x06status\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\x12&\n" +
	"\x0fhitl_request_id\x18\x04 \x01(\tR\rhitlRequestId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"P\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\x12\x11\n" +
	"\rHITL_REQUIRED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x03\"+\n" +
	"\x10WatchTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xc4\x02\n" +
	"\x11TaskProgressEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x124\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x1e.ai.v1.TaskProgressEvent.PhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fprogress_pct\x18\x04 \x01(\x05R\vprogressPct\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"i\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bPLANNING\x10\x01\x12\r\n" +
	"\tEXECUTING\x10\x02\x12\x11\n" +
	"\rAWAITING_HITL\x10\x03\x12\r\n" +
	"\tCOMPLETED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05\"\xc0\x01\n" +
	"\x11HITLSubmitRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x02R\triskScore\x12)\n" +
	"\x10approval_timeout\x18\x05 \x01(\tR\x0fapprovalTimeout\"w\n" +
	"\x12HITLSubmitResponse\x12&\n" +
	"\x0fhitl_request_id\x18\x01 \x01(\tR\rhitlRequestId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"@\n" +
	"\x16HITLGetDecisionRequest\x12&\n" +
	"\x0fhitl_request_id\x18\x01 \x01(\tR\rhitlRequestId\"\xae\x02\n" +
	"\x17HITLGetDecisionResponse\x12C\n" +
	"\bdecision\x18\x01 \x01(\x0e2'.ai.v1.HITLGetDecisionResponse.DecisionR\bdecision\x12\x1f\n" +
	"\vreviewer_id\x18\x02 \x01(\tR\n" +
	"reviewerId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"decided_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\"Z\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x03\x12\v\n" +
	"\aEXPIRED\x10\x042\x93\x01\n" +
	"\fAgentService\x12A\n" +
	"\n" +
	"SubmitTask\x12\x18.ai.v1.SubmitTaskRequest\x1a\x19.ai.v1.SubmitTaskResponse\x12@\n" +
	"\tWatchTask\x12\x17.ai.v1.WatchTaskRequest\x1a\x18.ai.v1.TaskProgressEvent0\x012\xa5\x01\n" +
	"\vHITLService\x12H\n" +
	"\x11SubmitForApproval\x12\x18.ai.v1.HITLSubmitRequest\x1a\x19.ai.v1.HITLSubmitResponse\x12L\n" +
	"\vGetDecision\x12\x1d.ai.v1.HITLGetDecisionRequest\x1a\x1e.ai.v1.HITLGetDecisionResponseBV\n" +
	"\x11com.yourorg.ai.v1B\x0eAiServiceProtoP\x01Z/github.com/yourorg/monorepo/api/grpc/ai/v1;aiv1b\x06proto3"

var (
	file_ai_service_proto_rawDescOnce sync.Once
	file_ai_service_proto_rawDescData []byte
)

func file_ai_service_proto_rawDescGZIP() []byte {
	file_ai_service_proto_rawDescOnce.Do(func() {
		file_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)))
	})
	return file_ai_service_proto_rawDescData
}

var file_ai_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ai_service_proto_goTypes = []any{
	(SubmitTaskResponse_Status)(0),        // 0: ai.v1.SubmitTaskResponse.Status
	(TaskProgressEvent_Phase)(0),          // 1: ai.v1.TaskProgressEvent.Phase
	(HITLGetDecisionResponse_Decision)(0), // 2: ai.v1.HITLGetDecisionResponse.Decision
	(*SubmitTaskRequest)(nil),             // 3: ai.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),            // 4: ai.v1.SubmitTaskResponse
	(*WatchTaskRequest)(nil),              // 5: ai.v1.WatchTaskRequest
	(*TaskProgressEvent)(nil),             // 6: ai.v1.TaskProgressEvent
	(*HITLSubmitRequest)(nil),             // 7: ai.v1.HITLSubmitRequest
	(*HITLSubmitResponse)(nil),            // 8: ai.v1.HITLSubmitResponse
	(*HITLGetDecisionRequest)(nil),        // 9: ai.v1.HITLGetDecisionRequest
	(*HITLGetDecisionResponse)(nil),       // 10: ai.v1.HITLGetDecisionResponse
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
}
var file_ai_service_proto_depIdxs = []int32{
	0,  // 0: ai.v1.SubmitTaskResponse.status:type_name -> ai.v1.SubmitTaskResponse.Status
	11, // 1: ai.v1.SubmitTaskResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: ai.v1.TaskProgressEvent.phase:type_name -> ai.v1.TaskProgressEvent.Phase
	11, // 3: ai.v1.TaskProgressEvent.timestamp:type_name -> google.protobuf.Timestamp
	11, // 4: ai.v1.HITLSubmitResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 5: ai.v1.HITLGetDecisionResponse.decision:type_name -> ai.v1.HITLGetDecisionResponse.Decision
	11, // 6: ai.v1.HITLGetDecisionResponse.decided_at:type_name -> google.protobuf.Timestamp
	3,  // 7: ai.v1.AgentService.SubmitTask:input_type -> ai.v1.SubmitTaskRequest
	5,  // 8: ai.v1.AgentService.WatchTask:input_type -> ai.v1.WatchTaskRequest
	7,  // 9: ai.v1.HITLService.SubmitForApproval:input_type -> ai.v1.HITLSubmitRequest
	9,  // 10: ai.v1.HITLService.GetDecision:input_type -> ai.v1.HITLGetDecisionRequest
	4,  // 11: ai.v1.AgentService.SubmitTask:output_type -> ai.v1.SubmitTaskResponse
	6,  // 12: ai.v1.AgentService.WatchTask:output_type -> ai.v1.TaskProgressEvent
	8,  // 13: ai.v1.HITLService.SubmitForApproval:output_type -> ai.v1.HITLSubmitResponse
	10, // 14: ai.v1.HITLService.GetDecision:output_type -> ai.v1.HITLGetDecisionResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ai_service_proto_init() }
func file_ai_service_proto_init() {
	if File_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ai_service_proto_goTypes,
		DependencyIndexes: file_ai_service_proto_depIdxs,
		EnumInfos:         file_ai_service_proto_enumTypes,
		MessageInfos:      file_ai_service_proto_msgTypes,
	}.Build()
	File_ai_service_proto = out.File
	file_ai_service_proto_goTypes = nil
	file_ai_service_proto_depIdxs = nil
}
