// ai_service.proto — gRPC contract for the AI Agent Service
// -----------------------------------------------------------
// This file is the source of truth for gRPC inter-service calls.
// Do NOT hand-write client or server stubs — generate them:
//
//   Go:     make gen-proto-go
//   Java:   mvn generate-sources  (protoc-maven-plugin)
//   Python: make gen-proto-python (grpcio-tools)
//
// When adding a new RPC:
//   1. Add the method and its request/response messages here.
//   2. Re-generate stubs for every language that consumes this service.
//   3. Update docs/api/grpc/README.md with the new method.
//
// Field numbering rules:
//   - Never reuse a field number once it has been released.
//   - Reserved numbers must be declared with `reserved` to prevent reuse.
//   - Use google.protobuf.Timestamp (not int64) for all timestamps.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: ai_service.proto

package aiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_SubmitTask_FullMethodName = "/ai.v1.AgentService/SubmitTask"
	AgentService_WatchTask_FullMethodName  = "/ai.v1.AgentService/WatchTask"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService provides synchronous gRPC methods for direct agent invocation.
// High-volume async flows use Kafka events (see asyncapi.yaml) instead.
type AgentServiceClient interface {
	// Submit a task to the agent and wait for a result (unary RPC).
	// Returns immediately with HITL_REQUIRED if human approval is needed.
	SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error)
	// Stream incremental progress updates for a long-running task (server streaming).
	WatchTask(ctx context.Context, in *WatchTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgressEvent], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) SubmitTask(ctx context.Context, in *SubmitTaskRequest, opts ...grpc.CallOption) (*SubmitTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTaskResponse)
	err := c.cc.Invoke(ctx, AgentService_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) WatchTask(ctx context.Context, in *WatchTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_WatchTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTaskRequest, TaskProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_WatchTaskClient = grpc.ServerStreamingClient[TaskProgressEvent]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService provides synchronous gRPC methods for direct agent invocation.
// High-volume async flows use Kafka events (see asyncapi.yaml) instead.
type AgentServiceServer interface {
	// Submit a task to the agent and wait for a result (unary RPC).
	// Returns immediately with HITL_REQUIRED if human approval is needed.
	SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error)
	// Stream incremental progress updates for a long-running task (server streaming).
	WatchTask(*WatchTaskRequest, grpc.ServerStreamingServer[TaskProgressEvent]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) SubmitTask(context.Context, *SubmitTaskRequest) (*SubmitTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedAgentServiceServer) WatchTask(*WatchTaskRequest, grpc.ServerStreamingServer[TaskProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchTask not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SubmitTask(ctx, req.(*SubmitTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_WatchTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).WatchTask(m, &grpc.GenericServerStream[WatchTaskRequest, TaskProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_WatchTaskServer = grpc.ServerStreamingServer[TaskProgressEvent]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTask",
			Handler:    _AgentService_SubmitTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTask",
			Handler:       _AgentService_WatchTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai_service.proto",
}

const (
	HITLService_SubmitForApproval_FullMethodName = "/ai.v1.HITLService/SubmitForApproval"
	HITLService_GetDecision_FullMethodName       = "/ai.v1.HITLService/GetDecision"
)

// HITLServiceClient is the client API for HITLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HITLService allows internal services to submit and poll HITL approval requests
// via gRPC (alternative to the REST /v1/hitl endpoints).
type HITLServiceClient interface {
	SubmitForApproval(ctx context.Context, in *HITLSubmitRequest, opts ...grpc.CallOption) (*HITLSubmitResponse, error)
	GetDecision(ctx context.Context, in *HITLGetDecisionRequest, opts ...grpc.CallOption) (*HITLGetDecisionResponse, error)
}

type hITLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHITLServiceClient(cc grpc.ClientConnInterface) HITLServiceClient {
	return &hITLServiceClient{cc}
}

func (c *hITLServiceClient) SubmitForApproval(ctx context.Context, in *HITLSubmitRequest, opts ...grpc.CallOption) (*HITLSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HITLSubmitResponse)
	err := c.cc.Invoke(ctx, HITLService_SubmitForApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hITLServiceClient) GetDecision(ctx context.Context, in *HITLGetDecisionRequest, opts ...grpc.CallOption) (*HITLGetDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HITLGetDecisionResponse)
	err := c.cc.Invoke(ctx, HITLService_GetDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HITLServiceServer is the server API for HITLService service.
// All implementations must embed UnimplementedHITLServiceServer
// for forward compatibility.
//
// HITLService allows internal services to submit and poll HITL approval requests
// via gRPC (alternative to the REST /v1/hitl endpoints).
type HITLServiceServer interface {
	SubmitForApproval(context.Context, *HITLSubmitRequest) (*HITLSubmitResponse, error)
	GetDecision(context.Context, *HITLGetDecisionRequest) (*HITLGetDecisionResponse, error)
	mustEmbedUnimplementedHITLServiceServer()
}

// UnimplementedHITLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHITLServiceServer struct{}

func (UnimplementedHITLServiceServer) SubmitForApproval(context.Context, *HITLSubmitRequest) (*HITLSubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitForApproval not implemented")
}
func (UnimplementedHITLServiceServer) GetDecision(context.Context, *HITLGetDecisionRequest) (*HITLGetDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecision not implemented")
}
func (UnimplementedHITLServiceServer) mustEmbedUnimplementedHITLServiceServer() {}
func (UnimplementedHITLServiceServer) testEmbeddedByValue()                     {}

// UnsafeHITLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HITLServiceServer will
// result in compilation errors.
type UnsafeHITLServiceServer interface {
	mustEmbedUnimplementedHITLServiceServer()
}

func RegisterHITLServiceServer(s grpc.ServiceRegistrar, srv HITLServiceServer) {
	// If the following call panics, it indicates UnimplementedHITLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HITLService_ServiceDesc, srv)
}

func _HITLService_SubmitForApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HITLSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HITLServiceServer).SubmitForApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HITLService_SubmitForApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HITLServiceServer).SubmitForApproval(ctx, req.(*HITLSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HITLService_GetDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HITLGetDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HITLServiceServer).GetDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HITLService_GetDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HITLServiceServer).GetDecision(ctx, req.(*HITLGetDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HITLService_ServiceDesc is the grpc.ServiceDesc for HITLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HITLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.HITLService",
	HandlerType: (*HITLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitForApproval",
			Handler:    _HITLService_SubmitForApproval_Handler,
		},
		{
			MethodName: "GetDecision",
			Handler:    _HITLService_GetDecision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_service.proto",
}
