replicaCount: 1

image:
  pullPolicy: Always

ingress:
  host: api.dev.example.com
  clusterIssuer: letsencrypt-staging

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 1

pdb:
  minAvailable: 0

env:
  APP_ENV: dev
  LOG_LEVEL: DEBUG
  HARNESS_MODE: solo
